openapi: 3.1.1
info:
  title: Pokemon API
  version: 1.0.0
  description: API for retrieving Pokemon data

paths:
  /pokemon/search:
    get:
      summary: Get Pokemon by name
      description: Retrieves a Pokemon's details based on their unique name.
      parameters:
        - name: name
          in: query
          required: true
          description: Name of the Pokemon to retrieve
          schema:
            type: string
            example: Charizard
      responses:
        "200":
          description: Successfully retrieved Pokemon
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pokemon'
              examples:
                example-1:
                  $ref: '#/components/schemas/Pokemon'
        "404":
          description: Pokemon not found
          content:
            application/json:
              example:

components:
  schemas:
    PokemonRegion:
      type: object
      properties:
        id:
          type: integer
          example: 2
        name:
          type: string
          example: Kanto
        population:
          type: integer
          example: 5000000
    Pokemon:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Charizard
        level:
          type: integer
          example: 36
        ability:
          type: string
          example: Blaze
        types:
          type: array
          items:
            type: string
            enum:
              - FIRE
              - WATER
              - GRASS
              - NORMAL
              - ELECTRIC
              - FLYING
              - FIGHTING
              - POISON
              - GROUND
              - PSYCHIC
              - ROCK
              - ICE
              - BUG
              - DRAGON
              - GHOST
              - DARK
              - STEEL
              - FAIRY
              - STELLAR
          example:
            - FIRE
            - DRAGON
        pokemonRegion:
          $ref: '#/components/schemas/PokemonRegion'
