openapi: 3.1.0
info:
  title: Pokemon API
  version: 1.0.0
  description: API for retrieving Pokemon data
#servers:
#  - url: http://www.pokemondb.com
#    description: Pokemon Database

paths:
  /pokemon/search:
    get:
      summary: Get Pokemon by name
      description: Retrieves a Pokemon's details based on their unique name.
      parameters:
        - name: id
          in: query
          required: false
          description: ID of the Pokemon to retrieve
          schema:
            type: integer
            example: 1
        - name: name
          in: query
          required: false
          description: Name of the Pokemon to retrieve
          schema:
            type: string
            example: Pikachu
      responses:
        200:
          description: Successfully retrieved Pokemon
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PokemonDto'
              examples:
                example-1:
                  $ref: '#/components/schemas/PokemonDto'
        404:
          description: Pokemon not found
          content:
            application/json:
              examples:
                example-1:
                  $ref: "#/components/examples/PokemonNotFoundByNameException"
  /pokemon/add:
    post:
      summary: Adds a new Pokemon
      description: 'Based on the validity of the region(could be name or id)
      it will search the region and add it to the mentioned information for the pokemon'
      requestBody:
        required: true
        description: ''
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PokemonDto"
      responses:
        201:
          description: Pokemon Created Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PokemonDto'
              examples:
                example-1:
                  $ref: '#/components/schemas/PokemonDto'

components:
  schemas:
    PokemonType:
      type: string
      description: "Available Pokémon types"
      enum:
        - FIRE
        - WATER
        - GRASS
        - NORMAL
        - ELECTRIC
        - FLYING
        - FIGHTING
        - POISON
        - GROUND
        - PSYCHIC
        - ROCK
        - ICE
        - BUG
        - DRAGON
        - GHOST
        - DARK
        - STEEL
        - FAIRY
        - STELLAR
    PokemonDto:
      type: object
      properties:
        name:
          type: string
          example: Charizard
        level:
          type: integer
          example: 10
        ability:
          type: string
          example: Blaze
        pokemonTypes:
          type: array
          items:
            $ref: "#/components/schemas/PokemonType"
          example:
            - FIRE
            - DRAGON
        regionName:
          type: string
          example: Kanto
        regionId:
          type: integer
          example: 1
  examples:
    PokemonNotFoundByNameException:
      value:
        httpStatusCode: NOT_FOUND
        message: Pokemon region with name 'Pika' was not found.